#!/usr/bin/env python3
"""Paperclip UI → Russian: translate ONLY multi-word phrases."""
import re, sys

# ONLY multi-word strings (containing space) — 100% safe, never in identifiers
TR = {
    "New Issue": "Новая задача",
    "Create Issue": "Создать задачу",
    "Open Issues": "Открытые задачи",
    "My Issues": "Мои задачи",
    "Create Issue": "Создать задачу",
    "Create Sub-Issue": "Создать подзадачу",
    "New project": "Новый проект",
    "New goal": "Новая цель",
    "New routine": "Новая процедура",
    "New Agent": "Новый агент",
    "New agent": "Новый агент",
    "Hire Agent": "Нанять агента",
    "Create Agent": "Создать агента",
    "Create Project": "Создать проект",
    "Create Goal": "Создать цель",
    "Create Routine": "Создать процедуру",
    "Create Skill": "Создать навык",
    "Create Account": "Создать аккаунт",
    "Add Agent": "Добавить агента",
    "Add Goal": "Добавить цель",
    "Add Project": "Добавить проект",
    "Add trigger": "Добавить триггер",
    "Add label": "Добавить метку",
    "Add environment": "Добавить окружение",
    "Save changes": "Сохранить изменения",
    "Save failed": "Ошибка сохранения",
    "Delete failed": "Ошибка удаления",
    "Update failed": "Ошибка обновления",
    "Create failed": "Ошибка создания",
    "Create secret": "Создать секрет",
    "Create skill": "Создать навык",
    "Remove skill": "Удалить навык",
    "Filter skills": "Фильтр навыков",
    "Set budget": "Установить бюджет",
    "Update budget": "Обновить бюджет",
    "Sign In": "Войти",
    "Sign in": "Войти",
    "Sign Out": "Выйти",
    "Sign out": "Выйти",
    "Try again": "Попробовать снова",
    "Get Started": "Начать работу",
    "Signed in": "Выполнен вход",
    "Coming soon": "Скоро",
    "Not Found": "Не найдено",
    "Page not found": "Страница не найдена",
    "No issues found.": "Задачи не найдены.",
    "No agents found.": "Агенты не найдены.",
    "No results found.": "Результаты не найдены.",
    "No projects found.": "Проекты не найдены.",
    "No goals yet.": "Целей пока нет.",
    "No routines yet.": "Процедур пока нет.",
    "No secrets yet.": "Секретов пока нет.",
    "No issues assigned to you.": "Нет назначенных вам задач.",
    "No new inbox items.": "Нет новых входящих.",
    "Inbox zero.": "Входящие пусты.",
    "Loading...": "Загрузка...",
    "Please try again.": "Попробуйте снова.",
    "Something went wrong": "Что-то пошло не так",
    "An error occurred": "Произошла ошибка",
    "Unexpected error": "Неожиданная ошибка",
    "Action failed": "Действие не удалось",
    "Request failed": "Запрос не удался",
    "The request failed.": "Запрос не выполнен.",
    "This field is required": "Обязательное поле",
    "Please fill in all required fields.": "Заполните все обязательные поля.",
    "Welcome to Paperclip": "Добро пожаловать в Paperclip",
    "Sign in to Paperclip": "Вход в Paperclip",
    "Already have an account?": "Уже есть аккаунт?",
    "Need an account?": "Нужен аккаунт?",
    "Create your account": "Создайте аккаунт",
    "Create your Paperclip account": "Создайте аккаунт Paperclip",
    "Back to inbox": "Назад к входящим",
    "Back to approvals": "Назад к согласованиям",
    "Go to inbox": "Перейти к входящим",
    "View inbox": "Просмотр входящих",
    "View agent": "Просмотр агента",
    "View profile": "Просмотр профиля",
    "View run": "Просмотр запуска",
    "Show more": "Показать больше",
    "Show less": "Показать меньше",
    "Show all": "Показать все",
    "Show full log": "Показать полный лог",
    "Hide full log": "Скрыть полный лог",
    "Show properties": "Показать свойства",
    "Show secret": "Показать секрет",
    "Show details": "Показать детали",
    "Hide details": "Скрыть детали",
    "Recent Runs": "Недавние запуски",
    "Active Agents": "Активные агенты",
    "Active / recent": "Активные / недавние",
    "Open Issues": "Открытые задачи",
    "My Issues": "Мои задачи",
    "Assigned to me": "Назначено мне",
    "Assign to me": "Назначить мне",
    "Assign to requester": "Назначить заявителю",
    "Assign tasks": "Назначать задачи",
    "CEO Agent": "Агент-CEO",
    "Default agent": "Агент по умолчанию",
    "Agent paused": "Агент приостановлен",
    "Agent resumed": "Агент возобновлён",
    "Agent paused by budget": "Агент приостановлен (бюджет)",
    "Agent was paused by budget limits": "Агент приостановлен из-за лимитов",
    "Agent heartbeats blocked by budget": "Пульс агента заблокирован",
    "Agent join request": "Заявка агента",
    "Agent options": "Параметры агента",
    "Agent sort": "Сортировка агентов",
    "Agent status dots": "Индикаторы статуса",
    "No Project": "Без проекта",
    "Project default": "Проект по умолчанию",
    "Routine created": "Процедура создана",
    "Routine saved": "Процедура сохранена",
    "Routine run started": "Запуск процедуры начат",
    "Routine run failed": "Запуск процедуры не удался",
    "Run routine": "Запустить процедуру",
    "Run now": "Запустить сейчас",
    "Skill created": "Навык создан",
    "Skill saved": "Навык сохранён",
    "Skill updated": "Навык обновлён",
    "Skill removed": "Навык удалён",
    "Skill creation failed": "Ошибка создания навыка",
    "Skill import failed": "Ошибка импорта навыка",
    "Secret created": "Секрет создан",
    "Secret deleted": "Секрет удалён",
    "Secret name": "Название секрета",
    "Budget healthy": "Бюджет в норме",
    "Budget warning": "Предупреждение бюджета",
    "Budget paused": "Бюджет приостановлен",
    "All-time tokens": "Токены за всё время",
    "Working directory": "Рабочая директория",
    "Local folder": "Локальная папка",
    "Set local folder": "Задать папку",
    "Change local folder": "Сменить папку",
    "Clear local folder": "Очистить папку",
    "GitHub repo": "Репозиторий GitHub",
    "Repo URL": "URL репозитория",
    "Clear repo": "Очистить репозиторий",
    "No Workspace": "Без области",
    "Start services": "Запустить службы",
    "Stop services": "Остановить службы",
    "Workspace name": "Название области",
    "Target date": "Дата цели",
    "No description": "Нет описания",
    "Not set": "Не задано",
    "None recorded": "Не записано",
    "Select company": "Выбрать компанию",
    "Select model": "Выбрать модель",
    "Select status": "Выбрать статус",
    "Select workspace": "Выбрать область",
    "Select an option": "Выбрать вариант",
    "This route does not exist.": "Этого маршрута не существует.",
    "Create one": "Создать",
}

PATTERNS = sorted(TR.keys(), key=len, reverse=True)
STRING_RE = re.compile(r'"[^"\\]*(?:\\.[^"\\]*)*"|\'[^\'\\]*(?:\\.[^\'\\]*)*\'')

def smart_translate(content):
    def replacer(m):
        full = m.group(0)
        inner = full[1:-1]
        if inner in TR:
            return full[0] + TR[inner] + full[0]
        return full
    return STRING_RE.sub(replacer, content)

if __name__ == "__main__":
    files = sys.argv[1:] if len(sys.argv) > 1 else [line.strip() for line in sys.stdin if line.strip()]
    translated = 0
    for fp in files:
        try:
            with open(fp, 'r') as f:
                orig = f.read()
            new = smart_translate(orig)
            if new != orig:
                with open(fp, 'w') as f:
                    f.write(new)
                translated += 1
        except:
            pass
    print("OK " + str(translated) + "/" + str(len(files)))
