#!/usr/bin/env python3
"""Paperclip UI → Russian: translate only multi-word phrases + safe single words."""
import re, sys

TR = {
    # NAVIGATION (safe - only in Sidebar.tsx as labels)
    "Dashboard": "Панель",
    "Inbox": "Входящие",
    "Issues": "Задачи",
    "Routines": "Процедуры",
    "Goals": "Цели",
    "Workspaces": "Области",
    "Projects": "Проекты",
    "Agents": "Агенты",
    "Org": "Оргструктура",
    "Skills": "Навыки",
    "Costs": "Расходы",
    "Activity": "Активность",
    "Settings": "Настройки",
    "Work": "Работа",
    "Company": "Компания",

    # STATUSES (safe - display only)
    "Blocked": "Заблокировано",
    "Error": "Ошибка",
    "Failed": "Ошибка",
    "Cancelled": "Отменено",
    "Completed": "Завершено",
    "Archived": "Архивировано",
    "Draft": "Черновик",
    "Paused": "Приостановлено",
    "Running": "Выполняется",
    "Stopped": "Остановлено",
    "Success": "Успешно",
    "Pending": "Ожидание",

    # ACTIONS (safe - button labels only)
    "Create": "Создать",
    "Add": "Добавить",
    "Edit": "Изменить",
    "Save": "Сохранить",
    "Cancel": "Отмена",
    "Close": "Закрыть",
    "Back": "Назад",
    "Next": "Далее",
    "Confirm": "Подтвердить",
    "Submit": "Отправить",
    "Approve": "Одобрить",
    "Reject": "Отклонить",
    "Archive": "Архивировать",
    "Copy": "Копировать",
    "Remove": "Удалить",
    "Update": "Обновить",
    "Send": "Отправить",
    "Start": "Начать",
    "Stop": "Остановить",
    "Clear": "Очистить",
    "Filter": "Фильтр",
    "Sort": "Сортировка",
    "All": "Все",
    "None": "Нет",

    # LABELS (safe - display only)
    "Title": "Название",
    "Description": "Описание",
    "Status": "Статус",
    "Priority": "Приоритет",
    "Assignee": "Исполнитель",
    "Reviewer": "Рецензент",
    "Approver": "Утверждающий",
    "Owner": "Владелец",
    "Parent": "Родитель",
    "Type": "Тип",
    "Search": "Поиск",
    "Board": "Совет",
    "Budget": "Бюджет",
    "Schedule": "Расписание",
    "History": "История",
    "Comments": "Комментарии",
    "Files": "Файлы",
    "Secrets": "Секреты",
    "Approvals": "Согласования",
    "References": "Ссылки",
    "Documents": "Документы",
    "Overview": "Обзор",
    "Details": "Детали",
    "Profile": "Профиль",
    "Tasks": "Задачи",
    "Task": "Задача",
    "Goal": "Цель",
    "Agent": "Агент",

    # MULTI-WORD PHRASES (100% safe - always UI text)
    "New Issue": "Новая задача",
    "Create Issue": "Создать задачу",
    "Create Agent": "Создать агента",
    "Create Project": "Создать проект",
    "Create Goal": "Создать цель",
    "Create Routine": "Создать процедуру",
    "Create Skill": "Создать навык",
    "Create Sub-Issue": "Создать подзадачу",
    "Add Agent": "Добавить агента",
    "Add Goal": "Добавить цель",
    "Add Project": "Добавить проект",
    "Add trigger": "Добавить триггер",
    "Add label": "Добавить метку",
    "Add environment": "Добавить окружение",
    "Save changes": "Сохранить изменения",
    "Save failed": "Ошибка сохранения",
    "Delete failed": "Ошибка удаления",
    "Update failed": "Ошибка обновления",
    "New project": "Новый проект",
    "New goal": "Новая цель",
    "New routine": "Новая процедура",
    "New Agent": "Новый агент",
    "New agent": "Новый агент",
    "Hire Agent": "Нанять агента",
    "Sign In": "Войти",
    "Sign in": "Войти",
    "Sign Out": "Выйти",
    "Sign out": "Выйти",
    "Sign in to Paperclip": "Вход в Paperclip",
    "Get Started": "Начать работу",
    "Try again": "Попробовать снова",
    "Page not found": "Страница не найдена",
    "No issues found.": "Задачи не найдены.",
    "No agents found.": "Агенты не найдены.",
    "No results found.": "Результаты не найдены.",
    "No projects found.": "Проекты не найдены.",
    "No goals yet.": "Целей пока нет.",
    "No routines yet.": "Процедур пока нет.",
    "No secrets yet.": "Секретов пока нет.",
    "Loading...": "Загрузка...",
    "Please try again.": "Попробуйте снова.",
    "Something went wrong": "Что-то пошло не так",
    "An error occurred": "Произошла ошибка",
    "Unexpected error": "Неожиданная ошибка",
    "Action failed": "Действие не удалось",
    "Request failed": "Запрос не удался",
    "The request failed.": "Запрос не выполнен.",
    "This field is required": "Обязательное поле",
    "Please fill in all required fields.": "Заполните все обязательные поля.",
    "Welcome to Paperclip": "Добро пожаловать в Paperclip",
    "Back to inbox": "Назад к входящим",
    "Back to approvals": "Назад к согласованиям",
    "Go to inbox": "Перейти к входящим",
    "View inbox": "Просмотр входящих",
    "View agent": "Просмотр агента",
    "View profile": "Просмотр профиля",
    "View run": "Просмотр запуска",
    "Show more": "Показать больше",
    "Show less": "Показать меньше",
    "Show all": "Показать все",
    "Show full log": "Показать полный лог",
    "Hide full log": "Скрыть полный лог",
    "Show properties": "Показать свойства",
    "Show secret": "Показать секрет",
    "Recent Runs": "Недавние запуски",
    "Active Agents": "Активные агенты",
    "Inbox zero.": "Входящие пусты.",
    "No new inbox items.": "Нет новых входящих.",
    "No issues assigned to you.": "Нет назначенных вам задач.",
    "No issues match your search.": "Нет задач по поиску.",
    "Open Issues": "Открытые задачи",
    "My Issues": "Мои задачи",
    "Assigned to me": "Назначено мне",
    "Assign to me": "Назначить мне",
    "Assign to requester": "Назначить заявителю",
    "Assign tasks": "Назначать задачи",
    "Default agent": "Агент по умолчанию",
    "Agent paused": "Агент приостановлен",
    "Agent resumed": "Агент возобновлён",
    "Agent paused by budget": "Агент приостановлен (бюджет)",
    "Agent was paused by budget limits": "Агент приостановлен из-за лимитов",
    "Agent heartbeats blocked by budget": "Пульс агента заблокирован",
    "Agent join request": "Заявка агента",
    "Agent options": "Параметры агента",
    "Agent sort": "Сортировка агентов",
    "Agent status dots": "Индикаторы статуса",
    "No Project": "Без проекта",
    "Project default": "Проект по умолчанию",
    "Routine created": "Процедура создана",
    "Routine saved": "Процедура сохранена",
    "Routine run started": "Запуск процедуры начат",
    "Routine run failed": "Запуск процедуры не удался",
    "Skill created": "Навык создан",
    "Skill saved": "Навык сохранён",
    "Skill updated": "Навык обновлён",
    "Skill removed": "Навык удалён",
    "Skill creation failed": "Ошибка создания навыка",
    "Skill import failed": "Ошибка импорта навыка",
    "Create skill": "Создать навык",
    "Remove skill": "Удалить навык",
    "Filter skills": "Фильтр навыков",
    "All-time tokens": "Токены за всё время",
    "Budget healthy": "Бюджет в норме",
    "Budget warning": "Предупреждение бюджета",
    "Budget paused": "Бюджет приостановлен",
    "Set budget": "Установить бюджет",
    "Update budget": "Обновить бюджет",
    "Working directory": "Рабочая директория",
    "Local folder": "Локальная папка",
    "Set local folder": "Задать папку",
    "Change local folder": "Сменить папку",
    "Clear local folder": "Очистить папку",
    "GitHub repo": "Репозиторий GitHub",
    "Repo URL": "URL репозитория",
    "Clear repo": "Очистить репозиторий",
    "No Workspace": "Без области",
    "Start services": "Запустить службы",
    "Stop services": "Остановить службы",
    "Create secret": "Создать секрет",
    "Secret created": "Секрет создан",
    "Secret deleted": "Секрет удалён",
    "Secret name": "Название секрета",
    "Target date": "Дата цели",
    "Workspace name": "Название области",
    "No description": "Нет описания",
    "Not set": "Не задано",
    "None recorded": "Не записано",
    "Already have an account?": "Уже есть аккаунт?",
    "Need an account?": "Нужен аккаунт?",
    "Create your account": "Создайте аккаунт",
    "Create Account": "Создать аккаунт",
    "Create your Paperclip account": "Создайте аккаунт Paperclip",
    "Select company": "Выбрать компанию",
    "Select model": "Выбрать модель",
    "Select status": "Выбрать статус",
    "Select workspace": "Выбрать область",
    "Select an option": "Выбрать вариант",
    "Create one": "Создать",
    "Signed in": "Выполнен вход",
    "Coming soon": "Скоро",
    "Not Found": "Не найдено",
    "This route does not exist.": "Этого маршрута не существует.",

    # CEO/Roles (safe)
    "CEO Agent": "Агент-CEO",
}

PATTERNS = sorted(TR.keys(), key=len, reverse=True)
_pat = re.compile('|'.join(re.escape(p) for p in PATTERNS))

STRING_RE = re.compile(r'"[^"\\]*(?:\\.[^"\\]*)*"|\'[^\'\\]*(?:\\.[^\'\\]*)*\'')

def smart_translate(content):
    def replacer(m):
        full = m.group(0)
        inner = full[1:-1]
        if inner in TR:
            return full[0] + TR[inner] + full[0]
        return full
    return STRING_RE.sub(replacer, content)

if __name__ == "__main__":
    files = sys.argv[1:] if len(sys.argv) > 1 else [line.strip() for line in sys.stdin if line.strip()]
    translated = 0
    for fp in files:
        try:
            with open(fp, 'r') as f:
                orig = f.read()
            new = smart_translate(orig)
            if new != orig:
                with open(fp, 'w') as f:
                    f.write(new)
                translated += 1
        except Exception as e:
            pass
    print("Translated " + str(translated) + "/" + str(len(files)) + " files")
