# Paperclip UI Russian translation dictionary
# Direct string replacement - same code, Russian text
TRANSLATIONS = {
    # === Nav & Core ===
    "Dashboard": "Панель управления",
    "Inbox": "Входящие",
    "Issues": "Задачи",
    "Routines": "Процедуры",
    "Goals": "Цели",
    "Workspaces": "Рабочие области",
    "Projects": "Проекты",
    "Agents": "Агенты",
    "Org": "Оргструктура",
    "Skills": "Навыки",
    "Costs": "Расходы",
    "Activity": "Активность",
    "Settings": "Настройки",
    "New Issue": "Новая задача",
    "Search": "Поиск",
    "Work": "Работа",
    "Company": "Компания",
    "Companies": "Компании",
    "Agent": "Агент",
    "CEO": "CEO",
    "CEO Agent": "Агент-CEO",
    "CFO": "CFO",
    "CTO": "CTO",
    "COO": "COO",
    "CMO": "CMO",
    "Engineer": "Инженер",
    "Human": "Человек",
    "Humans": "Люди",
    "Bot": "Бот",
    "Create": "Создать",
    "Add": "Добавить",
    "Edit": "Изменить",
    "Delete": "Удалить",
    "Save": "Сохранить",
    "Cancel": "Отмена",
    "Close": "Закрыть",
    "Back": "Назад",
    "Next": "Далее",
    "Confirm": "Подтвердить",
    "Submit": "Отправить",
    "Approve": "Одобрить",
    "Reject": "Отклонить",
    "Archive": "Архивировать",
    "Unarchive": "Разархивировать",
    "Copy": "Копировать",
    "Remove": "Удалить",
    "Update": "Обновить",
    "Refresh": "Обновить",
    "Send": "Отправить",
    "Test": "Проверить",
    "Run": "Запустить",
    "Start": "Начать",
    "Stop": "Остановить",
    "Sign In": "Войти",
    "Sign in": "Войти",
    "Sign Out": "Выйти",
    "Sign out": "Выйти",
    "Continue": "Продолжить",
    "Try again": "Попробовать снова",
    "Accept": "Принять",
    "Decline": "Отклонить",
    "Dismiss": "Закрыть",
    "Download": "Скачать",
    "Upload": "Загрузить",
    "Import": "Импорт",
    "Export": "Экспорт",
    "Retry": "Повторить",
    "Restart": "Перезапустить",
    "Reset": "Сбросить",
    "Pause": "Пауза",
    "Resume": "Продолжить",
    "Enable": "Включить",
    "Disable": "Отключить",
    "Yes": "Да",
    "No": "Нет",
    "Done": "Готово",
    "Ready": "Готово",
    "Clear": "Очистить",
    "Filter": "Фильтр",
    "Sort": "Сортировка",
    "All": "Все",
    "None": "Нет",
    "Default": "По умолчанию",
    "Custom": "Свой",
    "Auto": "Авто",
    "Required": "Обязательно",
    "Optional": "Опционально",
    "Unknown": "Неизвестно",
    "Unassigned": "Не назначен",
    "Unlimited": "Безлимит",
    "Unset": "Не задан",
    "None recorded": "Не записано",
    "Not set": "Не задано",
    "No description": "Нет описания",

    # === Statuses ===
    "Active": "Активен",
    "Blocked": "Заблокирован",
    "Cancelled": "Отменён",
    "Completed": "Завершён",
    "Archived": "Архивирован",
    "Draft": "Черновик",
    "Error": "Ошибка",
    "Failed": "Ошибка",
    "Paused": "Приостановлен",
    "Pending": "Ожидание",
    "Running": "Выполняется",
    "Started": "Запущен",
    "Stopped": "Остановлен",
    "Success": "Успешно",
    "Healthy": "Работает",
    "Unhealthy": "Не работает",
    "Warning": "Предупреждение",
    "Critical": "Критично",
    "High": "Высокий",
    "Low": "Низкий",
    "Medium": "Средний",

    # === Common actions ===
    "Create Issue": "Создать задачу",
    "Create Agent": "Создать агента",
    "Create Project": "Создать проект",
    "Create Goal": "Создать цель",
    "Create Routine": "Создать процедуру",
    "Create Skill": "Создать навык",
    "Create Sub-Issue": "Создать подзадачу",
    "Add Agent": "Добавить агента",
    "Add Goal": "Добавить цель",
    "Add Project": "Добавить проект",
    "Add trigger": "Добавить триггер",
    "Add label": "Добавить метку",
    "Add environment": "Добавить окружение",
    "Add item": "Добавить элемент",
    "Save changes": "Сохранить изменения",
    "Save failed": "Ошибка сохранения",
    "Delete failed": "Ошибка удаления",
    "Update failed": "Ошибка обновления",
    "Create failed": "Ошибка создания",

    # === Navigation ===
    "Back to inbox": "Назад к входящим",
    "Back to approvals": "Назад к согласованиям",
    "Go to inbox": "Перейти к входящим",
    "View inbox": "Просмотр входящих",
    "View agent": "Просмотр агента",
    "View profile": "Просмотр профиля",
    "View run": "Просмотр запуска",
    "View more": "Показать больше",
    "Show more": "Показать больше",
    "Show less": "Показать меньше",
    "Show all": "Показать все",
    "Show full log": "Показать полный лог",
    "Hide full log": "Скрыть полный лог",
    "Show details": "Показать детали",
    "Hide details": "Скрыть детали",
    "Show properties": "Показать свойства",
    "Show secret": "Показать секрет",

    # === Tabs/Sections ===
    "Overview": "Обзор",
    "Details": "Детали",
    "History": "История",
    "Comments": "Комментарии",
    "Tasks": "Задачи",
    "Task": "Задача",
    "Sub-issues": "Подзадачи",
    "References": "Ссылки",
    "Documents": "Документы",
    "Files": "Файлы",
    "Secrets": "Секреты",
    "Triggers": "Триггеры",
    "Approvals": "Согласования",
    "Approval": "Согласование",
    "Configuration": "Конфигурация",
    "Advanced": "Дополнительно",
    "General": "Общие",
    "Billing": "Биллинг",
    "Access": "Доступ",
    "Profile": "Профиль",
    "Budget": "Бюджет",
    "Schedule": "Расписание",
    "Board": "Совет",
    "Documentation": "Документация",

    # === Labels ===
    "Title": "Название",
    "Name": "Имя",
    "Email": "Почта",
    "Description": "Описание",
    "Status": "Статус",
    "Priority": "Приоритет",
    "Type": "Тип",
    "Scope": "Область",
    "Tags": "Метки",
    "Labels": "Ярлыки",
    "Assignee": "Исполнитель",
    "Assignees": "Исполнители",
    "Requester": "Заявитель",
    "Reviewer": "Рецензент",
    "Reviewers": "Рецензенты",
    "Approver": "Утверждающий",
    "Approvers": "Утверждающие",
    "Owner": "Владелец",
    "Parent": "Родитель",
    "Children": "Дочерние",
    "Target": "Цель",
    "Target date": "Дата цели",
    "Due date": "Срок",
    "Created": "Создано",
    "Updated": "Обновлено",
    "Archived": "Архивировано",
    "Version": "Версия",
    "Version history": "История версий",
    "Model": "Модель",
    "Provider": "Провайдер",
    "Adapter": "Адаптер",
    "Adapters": "Адаптеры",
    "Command": "Команда",
    "Commands": "Команды",
    "Environment": "Окружение",
    "Environments": "Окружения",
    "Workspace": "Рабочая область",
    "Workspace name": "Название области",
    "Execution workspace": "Область исполнения",
    "Workspace ID": "ID области",
    "Folder": "Папка",
    "Repo": "Репозиторий",
    "Branch": "Ветка",
    "Port": "Порт",
    "Host": "Хост",
    "Path": "Путь",
    "URL": "URL",
    "Secret": "Секрет",
    "Token": "Токен",
    "Key": "Ключ",
    "Value": "Значение",
    "Skill": "Навык",
    "Skill name": "Название навыка",

    # === Time ===
    "Today": "Сегодня",
    "Yesterday": "Вчера",
    "This week": "На этой неделе",
    "Last week": "На прошлой неделе",
    "This month": "В этом месяце",
    "Last month": "В прошлом месяце",
    "Now": "Сейчас",
    "Never": "Никогда",
    "Just now": "Только что",
    "Minutes ago": "минут назад",
    "Hours ago": "часов назад",
    "Days ago": "дней назад",

    # === Home / Login ===
    "Sign in to Paperclip": "Вход в Paperclip",
    "Sign in to continue": "Войдите чтобы продолжить",
    "Sign in and continue": "Войти и продолжить",
    "Create your account": "Создайте аккаунт",
    "Create Account": "Создать аккаунт",
    "Create your Paperclip account": "Создайте аккаунт Paperclip",
    "Already have an account?": "Уже есть аккаунт?",
    "Need an account?": "Нужен аккаунт?",
    "Welcome to Paperclip": "Добро пожаловать в Paperclip",
    "Get Started": "Начать",
    "Use your email and password to access this instance.": "Используйте email и пароль для входа.",
    "Signing in...": "Вход...",
    "Signing out...": "Выход...",
    "Signed in": "Выполнен вход",
    "Account": "Аккаунт",

    # === Dashboard ===
    "Dashboard": "Панель",
    "Recent": "Недавние",
    "Recent Runs": "Недавние запуски",
    "Active Agents": "Активные агенты",
    "Active / recent": "Активные / недавние",

    # === Issues ===
    "Inbox zero.": "Входящие пусты.",
    "No new inbox items.": "Нет новых входящих.",
    "No issues assigned to you.": "Нет назначенных вам задач.",
    "No issues match your search.": "Нет задач по вашему поиску.",
    "No issues match the current filters or search.": "Нет задач по текущим фильтрам.",
    "Create one": "Создать задачу",
    "Create your first issue": "Создайте первую задачу",
    "Issue": "Задача",
    "Sub-issue": "Подзадача",
    "New issue": "Новая задача",
    "Open Issues": "Открытые задачи",
    "My Issues": "Мои задачи",
    "Assigned to me": "Назначено мне",
    "Assign to me": "Назначить мне",
    "Assign to requester": "Назначить заявителю",
    "Assign scoped tasks": "Назначать задачи",
    "Assign tasks": "Назначать задачи",
    "Assign an agent": "Назначить агента",

    # === Agents ===
    "Hire Agent": "Нанять агента",
    "New Agent": "Новый агент",
    "New agent": "Новый агент",
    "Agent name": "Имя агента",
    "Agent paused": "Агент приостановлен",
    "Agent resumed": "Агент возобновлён",
    "Agent paused by budget": "Агент приостановлен (бюджет)",
    "Agent was paused by budget limits": "Агент приостановлен из-за лимитов",
    "Agent heartbeats blocked by budget": "Пульс агента заблокирован (бюджет)",
    "Agent join request": "Заявка агента",
    "Agent instructions file": "Файл инструкций агента",
    "Agent options": "Параметры агента",
    "Agent sort": "Сортировка агентов",
    "Agent status dots": "Индикаторы статуса",
    "Hire your first agent": "Наймите первого агента",
    "Choose agent when running": "Выбор агента при запуске",
    "Select agent": "Выбрать агента",
    "Select an agent": "Выбрать агента",
    "Browse agents": "Обзор агентов",
    "No agents found.": "Агенты не найдены.",
    "Set a default agent before enabling routine automation.": "Назначьте агента по умолчанию.",
    "Default agent": "Агент по умолчанию",
    "Default agent required": "Требуется агент по умолчанию",
    "Default agent set": "Агент по умолчанию задан",

    # === Projects ===
    "New project": "Новый проект",
    "Project name": "Название проекта",
    "No projects found.": "Проекты не найдены.",
    "No projects yet.": "Пока нет проектов.",
    "Browse projects": "Обзор проектов",
    "No Project": "Без проекта",
    "Project default": "По умолчанию проекта",
    "Project default environment": "Среда проекта по умолчанию",
    "Project execution blocked by budget": "Исполнение проекта заблокировано (бюджет)",
    "Project paused by budget": "Проект приостановлен (бюджет)",
    "Project skill scan complete": "Сканирование навыков завершено",
    "Project skill scan failed": "Сканирование навыков не удалось",
    "Project sort": "Сортировка проектов",
    "Project workspace": "Область проекта",
    "Projects section actions": "Действия раздела проектов",

    # === Goals ===
    "Goal": "Цель",
    "Goal title": "Название цели",
    "New goal": "Новая цель",
    "New sub-goal": "Новая подцель",
    "No goals yet.": "Пока нет целей.",
    "Create goal": "Создать цель",
    "Parent Goal": "Родительская цель",
    "Parent goal": "Родительская цель",

    # === Routines ===
    "Routine": "Процедура",
    "Routine title": "Название процедуры",
    "Routine created": "Процедура создана",
    "Routine saved": "Процедура сохранена",
    "Routine deleted": "Процедура удалена",
    "Routine not found": "Процедура не найдена",
    "Routine run started": "Запуск процедуры начат",
    "Routine run failed": "Запуск процедуры не удался",
    "Routine changed": "Процедура изменена",
    "New routine": "Новая процедура",
    "No routines yet.": "Пока нет процедур.",
    "Run routine": "Запустить процедуру",
    "Run now": "Запустить сейчас",

    # === Skills ===
    "Skill created": "Навык создан",
    "Skill saved": "Навык сохранён",
    "Skill updated": "Навык обновлён",
    "Skill removed": "Навык удалён",
    "Skill creation failed": "Ошибка создания навыка",
    "Skill import failed": "Ошибка импорта навыка",
    "Skill conflicts found": "Найдены конфликты навыков",
    "Skills imported": "Навыки импортированы",
    "Create skill": "Создать навык",
    "Remove skill": "Удалить навык",
    "Detach this skill from all agents before removing it.": "Открепите навык от всех агентов перед удалением.",
    "You are about to remove this skill.": "Вы собираетесь удалить этот навык.",
    "Filter skills": "Фильтр навыков",
    "Refreshing skills list...": "Обновление списка навыков...",
    "Built-in": "Встроенный",
    "Plugin": "Плагин",

    # === Costs ===
    "Usage": "Использование",
    "Cost": "Стоимость",
    "Credits": "Кредиты",
    "Debits": "Списания",
    "Net": "Чистый",
    "Spend": "Траты",
    "Period spend": "Траты за период",
    "All-time tokens": "Токены за всё время",
    "Finance ledger": "Финансовый журнал",
    "Finance events": "Финансовые события",
    "Finance net": "Чистый баланс",
    "USD": "USD",

    # === Budget ===
    "Budget healthy": "Бюджет в норме",
    "Budget warning": "Предупреждение бюджета",
    "Budget paused": "Бюджет приостановлен",
    "Under budget": "В рамках бюджета",
    "Over budget": "Превышен бюджет",
    "Unlimited budget": "Безлимитный бюджет",
    "No cap configured": "Лимит не задан",
    "Set budget": "Установить бюджет",
    "Update budget": "Обновить бюджет",
    "Raise budget": "Увеличить бюджет",
    "Raise budget & resume": "Увеличить и продолжить",

    # === Workspaces ===
    "Working directory": "Рабочая директория",
    "Working dir": "Рабочая папка",
    "Local folder": "Локальная папка",
    "Set local folder": "Задать папку",
    "Change local folder": "Сменить папку",
    "Clear local folder": "Очистить папку",
    "Remote git repo": "Удалённый репозиторий",
    "GitHub repo": "Репозиторий GitHub",
    "Repo URL": "URL репозитория",
    "Repo ref": "Ссылка репозитория",
    "Clear repo": "Очистить репозиторий",
    "Execution or project workspace used for the issue.": "Рабочая область для задачи.",
    "Reuse existing workspace": "Переиспользовать область",
    "Reused existing workspace": "Область переиспользована",
    "This workspace is disposable and can be archived.": "Область одноразовая, можно архивировать.",
    "No Workspace": "Без области",
    "Start services": "Запустить службы",
    "Stop services": "Остановить службы",

    # === Secrets ===
    "Create secret": "Создать секрет",
    "Secret created": "Секрет создан",
    "Secret deleted": "Секрет удалён",
    "Secret name": "Название секрета",
    "Secret value": "Значение секрета",
    "Update secret value": "Обновить значение",
    "No secrets yet.": "Пока нет секретов.",
    "No secrets match your filters.": "Нет секретов по фильтрам.",
    "No matching secrets. Create one to bind it here.": "Нет подходящих секретов.",

    # === Notifications ===
    "No new notifications": "Нет новых уведомлений",
    "No activity yet.": "Пока нет активности.",
    "No recent activity": "Нет недавней активности",
    "No notifications": "Нет уведомлений",

    # === Misc ===
    "Paperclip": "Paperclip",
    "Loading...": "Загрузка...",
    "Loading": "Загрузка",
    "Please wait...": "Пожалуйста, подождите...",
    "Please try again.": "Пожалуйста, попробуйте снова.",
    "Something went wrong": "Что-то пошло не так",
    "An error occurred": "Произошла ошибка",
    "Unexpected error": "Неожиданная ошибка",
    "Try again": "Попробовать снова",
    "Action failed": "Действие не удалось",
    "Request failed": "Запрос не удался",
    "The request failed.": "Запрос не выполнен.",
    "Operation failed": "Операция не удалась",
    "Please fill in all required fields.": "Заполните все обязательные поля.",
    "This field is required": "Обязательное поле",
    "No results found.": "Результаты не найдены.",
    "No data available": "Нет данных",
    "Not available": "Недоступно",
    "Unavailable": "Недоступно",
    "Coming soon": "Скоро",
    "Preview": "Предпросмотр",
    "Page not found": "Страница не найдена",
    "This route does not exist.": "Этого маршрута не существует.",
    "Not Found": "Не найдено",
    "Select...": "Выбрать...",
    "Choose...": "Выбрать...",
    "Pick...": "Выбрать...",
    "Select an option": "Выберите вариант",
    "Select a value": "Выберите значение",
    "Select status": "Выберите статус",
    "Select company": "Выберите компанию",
    "Select model": "Выберите модель",
    "Select workspace": "Выберите область",
}

# Apply the translations
if __name__ == "__main__":
    import sys
    files = sys.argv[1:] if len(sys.argv) > 1 else [line.strip() for line in sys.stdin if line.strip()]
    total = len(files)
    translated = 0
    for filepath in files:
        try:
            with open(filepath, 'r') as f:
                content = f.read()
            original = content
            for en, ru in TRANSLATIONS.items():
                if en in content:
                    content = content.replace(en, ru)
            if content != original:
                with open(filepath, 'w') as f:
                    f.write(content)
                translated += 1
        except Exception as e:
            print(f"Error {filepath}: {e}", file=sys.stderr)
    print(f"Translated {translated}/{total} files")
