import {
  Atom,
  Бот,
  Brain,
  Bug,
  CircuitСовет,
  Code,
  Cog,
  Cpu,
  Crown,
  Database,
  Eye,
  FileCode,
  Fingerprint,
  Flame,
  Gem,
  GitВетка,
  Globe,
  Hammer,
  Heart,
  Hexagon,
  Lightbulb,
  Lock,
  Mail,
  MessageSquare,
  Microscope,
  Package,
  Pentagon,
  Puzzle,
  Radar,
  Rocket,
  Поиск,
  Shield,
  Sparkles,
  Star,
  Swords,
  Цель,
  Telescope,
  Terminal,
  Wand2,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { AGENT_ICON_NAMES, type АгентIconИмя } from "@paperclipai/shared";

export const AGENT_ICONS: Record<АгентIconИмя, LucideIcon> = {
  bot: Бот,
  cpu: Cpu,
  brain: Brain,
  zap: Zap,
  rocket: Rocket,
  code: Code,
  terminal: Terminal,
  shield: Shield,
  eye: Eye,
  search: Поиск,
  wrench: Wrench,
  hammer: Hammer,
  lightbulb: Lightbulb,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  flame: Flame,
  bug: Bug,
  cog: Cog,
  database: Database,
  globe: Globe,
  lock: Lock,
  mail: Mail,
  "message-square": MessageSquare,
  "file-code": FileCode,
  "git-branch": GitВетка,
  package: Package,
  puzzle: Puzzle,
  target: Цель,
  wand: Wand2,
  atom: Atom,
  "circuit-board": CircuitСовет,
  radar: Radar,
  swords: Swords,
  telescope: Telescope,
  microscope: Microscope,
  crown: Crown,
  gem: Gem,
  hexagon: Hexagon,
  pentagon: Pentagon,
  fingerprint: Fingerprint,
};

const DEFAULT_ICON: АгентIconИмя = "bot";

export function getАгентIcon(iconИмя: string | null | undefined): LucideIcon {
  if (iconИмя && AGENT_ICON_NAMES.includes(iconИмя as АгентIconИмя)) {
    return AGENT_ICONS[iconИмя as АгентIconИмя];
  }
  return AGENT_ICONS[DEFAULT_ICON];
}
