import type { СоздатьConfigЗначениеs } from "@paperclipai/adapter-utils";

export const defaultСоздатьЗначениеs: СоздатьConfigЗначениеs = {
  adapterТип: "claude_local",
  cwd: "",
  instructionsFileПуть: "",
  promptTemplate: "",
  model: "",
  thinkingEffort: "",
  chrome: false,
  dangerouslySkipPermissions: true,
  search: false,
  fastMode: false,
  dangerouslyBypassSandbox: false,
  command: "",
  args: "",
  extraArgs: "",
  envVars: "",
  envBindings: {},
  url: "",
  bootstrapPrompt: "",
  payloadTemplateJson: "",
  workspaceStrategyТип: "project_primary",
  workspaceBaseRef: "",
  workspaceВеткаTemplate: "",
  worktreeРодительDir: "",
  runtimeServicesJson: "",
  maxTurnsPerЗапустить: 1000,
  heartbeatВключитьd: false,
  intervalSec: 300,
};
